"""
Report generation engine for Kanvas: coordinates HTML and Markdown export from
workbook data, column selections, and optional visualizations. Cross-platform
(Windows, macOS, Linux). Revised on 01/02/2026 by Jinto Antony
"""

import logging
from datetime import datetime
from typing import Any, Dict, List

import pandas as pd

from helper import config
from helper.reporting.html_exporter import HTMLExporter

logger = logging.getLogger(__name__)

REPORT_TYPES = ("HTML", "Markdown")
MAX_MD_TABLE_ROWS = 1000
CELL_DISPLAY_MAX = 100
CELL_TRUNCATE_SUFFIX_LEN = 3


SHEET_DISPLAY_NAMES = {
    config.SHEET_ACCOUNTS: "Compromised Accounts",
    config.SHEET_SYSTEMS: "Compromised Systems",
    config.SHEET_INDICATORS: "IOC (Indicators of Compromise)",
}


class MarkdownExporter:

    def get_sheet_display_name(self, sheet_name: str) -> str:
        sheet_lower = sheet_name.lower()
        for key, display_name in SHEET_DISPLAY_NAMES.items():
            if sheet_lower == key.lower():
                return display_name
        return sheet_name

    def export(self, report_data: Dict[str, Any], output_path: str) -> bool:
        try:
            markdown_content = self.build_markdown(report_data)
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(markdown_content)
            logger.info("Markdown report exported successfully to %s", output_path)
            return True
        except Exception as e:
            logger.error("Error exporting to Markdown: %s", e)
            return False

    def build_markdown(self, report_data: Dict[str, Any]) -> str:
        title = report_data.get("title", "KANVAS Report")
        author = report_data.get("author", "KANVAS User")
        summary = report_data.get("summary", "No summary provided.")
        excel_file_name = report_data.get("excel_file_name", "N/A")
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        md = f"""# {title}

---

## Report Information

- **Author:** {author}
- **Generated On:** {timestamp}
- **Source Excel File:** {excel_file_name}

---

## Executive Summary

{summary}

---

"""
        for sheet_name, sheet_data in report_data.get("sheets", {}).items():
            display_name = self.get_sheet_display_name(sheet_name)
            md += f"""## {display_name}

"""
            df = pd.DataFrame(sheet_data['data'], columns=sheet_data['columns'])
            if not df.empty:
                md += f"**Total Rows:** {len(df)}\n\n"
                md += "### Data Table\n\n"
                headers = df.columns.tolist()
                md += "| " + " | ".join(str(h) for h in headers) + " |\n"
                md += "| " + " | ".join(["---"] * len(headers)) + " |\n"
                max_rows = min(MAX_MD_TABLE_ROWS, len(df))
                for idx, row in df.head(max_rows).iterrows():
                    row_values = []
                    for col in headers:
                        value = str(row[col]) if pd.notna(row[col]) else ""
                        value = value.replace("|", "\\|").replace("\n", " ").replace("\r", " ")
                        if len(value) > CELL_DISPLAY_MAX:
                            value = value[:CELL_DISPLAY_MAX - CELL_TRUNCATE_SUFFIX_LEN] + "..."
                        row_values.append(value)
                    md += "| " + " | ".join(row_values) + " |\n"
                if len(df) > max_rows:
                    md += "\n*Note: Showing first %s of %s rows. Full data available in source Excel file.*\n" % (max_rows, len(df))
                md += "\n---\n\n"
            else:
                md += "*No data available in this sheet.*\n\n---\n\n"
        md += f"""
---

## Report Footer

*This report was generated by KANVAS on {timestamp}*

*For questions or issues, please contact the report author: {author}*

---
"""
        return md


class ReportEngine:

    def __init__(self, parent=None, db_path: str = None):
        self.parent = parent
        self.db_path = db_path or ""
        self.exporters = {"HTML": None, "Markdown": None}

    def generate_report(self, report_type: str, workbook, file_path: str, output_path: str,
                        selected_sheets: List[str], report_title: str = "KANVAS Report",
                        author: str = "KANVAS User", summary: str = "",
                        column_selections: Dict[str, List[str]] = None,
                        selected_sections: Dict[str, bool] = None,
                        timeline_image_path: str = None,
                        network_image_path: str = None,
                        html_template: str = "detailed",
                        recommendations_file_path: str = None,
                        recommendations_content: str = None,
                        investigation_summary_file_path: str = None,
                        images_constrained: bool = True,
                        report_full_width: bool = False,
                        header_options: Dict[str, bool] = None,
                        footer_options: Dict[str, bool] = None,
                        report_font: str = "Inter",
                        report_color: str = "#235AAA") -> bool:
        if report_type not in REPORT_TYPES:
            logger.error("Unsupported report type: %s. Only HTML and Markdown are supported.", report_type)
            return False
        try:
            report_data = {
                "title": report_title,
                "author": author,
                "summary": summary,
                "excel_file_name": file_path,
                "workbook": workbook,
                "db_path": self.db_path,
                "sheets": {},
                "timeline_image_path": timeline_image_path,
                "network_image_path": network_image_path,
                "html_template": html_template,
                "recommendations_file_path": recommendations_file_path,
                "recommendations_content": recommendations_content,
                "investigation_summary_file_path": investigation_summary_file_path,
                "images_constrained": images_constrained,
                "report_full_width": report_full_width,
                "header_options": header_options or {},
                "footer_options": footer_options or {},
                "report_font": report_font,
                "report_color": report_color,
                "selected_sections": selected_sections or {},
                "enable_visualizations": bool(selected_sheets),
            }
            column_selections = column_selections or {}
            for sheet_name in selected_sheets:
                if sheet_name not in workbook.sheetnames:
                    logger.warning("Sheet '%s' not found in workbook.", sheet_name)
                    continue
                df = self.get_sheet_data(workbook, sheet_name)
                if not df.empty:
                    selected_cols = column_selections.get(sheet_name)
                    if selected_cols:
                        available_cols = [col for col in selected_cols if col in df.columns]
                        if available_cols:
                            df = df[available_cols]
                        else:
                            logger.warning("None of the selected columns found in sheet '%s', using all columns.", sheet_name)
                    report_data["sheets"][sheet_name] = {
                        'data': df.values.tolist(),
                        'columns': df.columns.tolist()
                    }
            if report_type == "HTML":
                exporter = HTMLExporter()
                return exporter.export(report_data, output_path, template=report_data.get("html_template", "detailed"))
            if report_type == "Markdown":
                exporter = MarkdownExporter()
                return exporter.export(report_data, output_path)
        except Exception as e:
            logger.exception("Error generating %s report: %s", report_type, e)
            return False

    def get_sheet_data(self, workbook, sheet_name: str) -> pd.DataFrame:
        try:
            if sheet_name not in workbook.sheetnames:
                logger.warning("Sheet '%s' not found in workbook.", sheet_name)
                return pd.DataFrame()
            sheet = workbook[sheet_name]
            headers = [str(sheet.cell(row=1, column=col).value or "Column %s" % col) for col in range(1, sheet.max_column + 1)]
            data = []
            for row_idx in range(2, sheet.max_row + 1):
                data.append([sheet.cell(row=row_idx, column=col).value for col in range(1, sheet.max_column + 1)])
            return pd.DataFrame(data, columns=headers)
        except Exception as e:
            logger.error("Error loading sheet '%s': %s", sheet_name, e)
            return pd.DataFrame()
